### PR TITLE
feat: added basic custom visualization

### PR DESCRIPTION
**Pull request by ErikBjare**
Intended to be used with the experimental custom_static/custom visualizations feature: https://github.com/ActivityWatch/aw-server/pull/83

### CODE REVIEW

**Comment by Alwinator** [comment]
@ErikBjare Looks great ;)

**Comment by ErikBjare** [comment]
@Alwinator Good catch!

**Comment by Alwinator** [comment]
@ErikBjare Thanks :)

**Comment by Alwinator** [comment]
@ErikBjare You can also replace 'stop' to 'end' in the console.log ;)

**Pull request merged**
